### ISSUE TITLE
Cloning in Sparse Mode Still Has Bugs

### ISSUE THREAD

**Issue by adam-beck** [derrickstolee/sparse-checkout-example#15]
Context: https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/#sparse-mode
Git Version: 2.27.0
OS: Ubuntu 20.10

**Steps to Reproduce**

1. `$ git clone --no-checkout https://github.com/derrickstolee/sparse-checkout-example`
2. `$ cd sparse-checkout-example/`
3. `$ git sparse-checkout init --cone`
4. `$ git checkout main`
    1. Problem may arise here. Git logs all the files in the repo along with other pieces of infromation. A subset of the log is below
    2. > $ git checkout main
            D       LICENSE.md
            D       README.md
            D       bootstrap.sh
D       client/README
D       client/android/.gitignore
D       client/android/README.md
D       client/android/app.js
D       client/android/auth.js
D       client/android/config.js
D       client/android/images/login.png
D       client/android/images/preview.png
D       client/android/package-lock.json
D       client/android/package.json
...
D       web/friends/images/bg.jpg
D       web/friends/images/overlay.png
D       web/friends/images/pic01.jpg
D       web/friends/images/pic02.jpg
D       web/friends/images/pic03.jpg
D       web/friends/index.html
Already on 'main'
Your branch is up to date with 'origin/main'.
5. `$ ls`
    1. **No files listed**

**Comment by derrickstolee** [comment]
> Context: https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/#sparse-mode
> Git Version: 2.27.0

Please update to a more recent version of Git, as this is fixed in later versions.

**Comment by adam-beck** [comment]
Agh sorry! I thought I was on the latest.
